### ISSUE TITLE
Licensing for the adware definition files?

### ISSUE THREAD

**Issue by etresoft** [sheagcraig/SavingThrow#13]
In a private forum, the author of MalwareBytes for Mac (originally Adware Medic) has claimed that most of these definitions were copied from the old Adware Medic signature file. Can anyone confirm or deny this?

I was thinking about incorporating these definitions into my own project, EtreCheck. I am taking a different approach by identifying a whitelist of known, legitimate Mac software. But I am also interested in positively identifying anything that is known to be adware. EtreCheck is also GPL so our data should be compatible as long as you have a clear license to the adware definition files. Otherwise, I am building my own blacklist via user submissions. I will be adding that to the EtreCheck source once it develops a bit.

Thanks,
John Daniel

**Comment by sheagcraig** [comment]
Most of these definitions are the result of a user submission based on the old Adware Medic signature file. As I understand it, Thomas Reed is not worried about it, as they are now pretty out-of-date. Whether this is an acceptable source for inclusion in a GPL'ed project, I cannot say!

Moving forward, any contributions that you would like to make towards the SavingThrows organization's definitions would of course be welcomed.
