### ISSUE TITLE
Genieo

### ISSUE THREAD

**Issue by beckf** [sheagcraig/SavingThrow#14]
I have several machines where SavingThrow cannot remove the LaunchAgent file /Users/*/Library/LaunchAgents/Javeview.update.plist.  The file is properly identified in the ADF file, but SavingThrow cannot delete/quarantine the file.  I am trying to get my hands on one of the computers and once I do I can troubleshoot some more.  The operation not permitted will hint there is a permissions issue, but SavingThrow is being run as root and other files in Application Support get removed/quarantined just fine.

Here is SavingThrows verbose output:
Unloading /Users/username/Library/LaunchAgents/Javeview.update.plist
Launchctl response: /Users/username/Library/LaunchAgents/Javeview.update.plist: Could not find specified service
Failed to remove file: Genieo:/Users/username/Library/LaunchAgents/Javeview.update.plist Error: [Errno 1] Operation not permitted: '/Users/username/Library/LaunchAgents/Javeview.update.plist'

**Comment by sheagcraig** [comment]
Any update on this @beckf?

**Comment by jlrobin3** [comment]
Noticed the same issue here - turns out that the files in question had the user immutable flag set.
