### ISSUE TITLE
Ability to parse Adware Medic's signatures file

### ISSUE THREAD

**Issue by homebysix** [sheagcraig/SavingThrow#3]
http://www.adwaremedic.com/signatures.xml

(A) Are there any useful definitions that can be gleaned from this signatures file and added to a SavingThrow .adf?

\- or -

(B) If we as a community trust Adware Medic sufficiently, would it make sense for SavingThrow to directly parse the above-linked .xml file?

**Comment by opragel** [comment]
I don't expect the signature file to be updated now that Adware Medic has become part of Malwarebytes.

Have a feeling the file below still has significant issues, but linked below is a rough partial extract/conversion of the Adware Medic signatures:

https://gist.github.com/opragel/2da6ae2fcc4488653e55#file-adwaremedic-signatures-modified-xml

**Comment by YesThatAllen** [comment]
The last update to the signatures included:`unsupported="true"`

> `<admedicsigs unsupported="true" version="96" modified="2015-9-19">`

And the file hasn't changed since September. I don't feel there's a need to handle that file anymore.
